<?php

namespace ContainerVWesYNC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KVmSvxyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kVmSvxy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kVmSvxy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lignepanierRepository' => ['privates', 'App\\Repository\\LignepanierRepository', 'getLignepanierRepositoryService', true],
            'product' => ['privates', '.errored..service_locator.kVmSvxy.App\\Entity\\Produits', NULL, 'Cannot autowire service ".service_locator.kVmSvxy": it references class "App\\Entity\\Produits" but no such service exists.'],
            'produitRep' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
        ], [
            'entityManager' => '?',
            'lignepanierRepository' => 'App\\Repository\\LignepanierRepository',
            'product' => 'App\\Entity\\Produits',
            'produitRep' => 'App\\Repository\\ProduitsRepository',
        ]);
    }
}
