<?php

namespace ContainerOd62bUC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBan3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4WM7mxr.App\Entity\Ban' shared service.
     *
     * @return \App\Entity\Ban
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.4WM7mxr": it references class "App\\Entity\\Ban" but no such service exists.');
    }
}
