<?php

namespace ContainerPLSgpxu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FTwUYIWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fTwUYIW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fTwUYIW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allusersRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
            'comment' => ['privates', '.errored..service_locator.fTwUYIW.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.fTwUYIW": it references class "App\\Entity\\Comment" but no such service exists.'],
        ], [
            'allusersRepository' => 'App\\Repository\\AllusersRepository',
            'comment' => 'App\\Entity\\Comment',
        ]);
    }
}
