<?php

namespace ContainerPNS86Vh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_G0b75OoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.G0b75Oo' shared service.
     *
     * @return \App\Controller\ManagerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\LignepanierController::delete()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?');
    }
}
