<?php

namespace ContainerPNS86Vh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GJQFHAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GJQFH_A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GJQFH_A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['privates', '.errored.G0b75Oo', NULL, 'Cannot determine controller argument for "App\\Controller\\LignepanierController::delete()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?'],
            'rep' => ['privates', 'App\\Repository\\LignepanierRepository', 'getLignepanierRepositoryService', true],
        ], [
            'doctrine' => '?',
            'rep' => 'App\\Repository\\LignepanierRepository',
        ]);
    }
}
