<?php

namespace ContainerDpn7Jat;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChallengeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GHI_RB_.App\Entity\Challenge' shared service.
     *
     * @return \App\Entity\Challenge
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.GHI_RB_": it references class "App\\Entity\\Challenge" but no such service exists.');
    }
}
