<?php

namespace ContainerYTCYtws;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsTranslation_ConfigFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'jms_translation.config_factory' shared service.
     *
     * @return \JMS\TranslationBundle\Translation\ConfigFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'jms'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ConfigFactory.php';

        return $container->services['jms_translation.config_factory'] = new \JMS\TranslationBundle\Translation\ConfigFactory([]);
    }
}
