<?php

namespace Container2XUAcFU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaginatorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.d2aKKvm.knp\Component\Pager\PaginatorInterface' shared service.
     *
     * @return \knp\Component\Pager\PaginatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.d2aKKvm": it references interface "knp\\Component\\Pager\\PaginatorInterface" but no such service exists. Did you mean "Knp\\Component\\Pager\\PaginatorInterface"?');
    }
}
