<?php

namespace Container2XUAcFU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTutorielService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0Z.rFm1.App\Entity\Tutoriel' shared service.
     *
     * @return \App\Entity\Tutoriel
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0Z.rFm1": it references class "App\\Entity\\Tutoriel" but no such service exists.');
    }
}
