<?php

namespace ContainerHmifXZe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavorisTuroial2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zBuIoHb.App\Entity\FavorisTuroial' shared service.
     *
     * @return \App\Entity\FavorisTuroial
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zBuIoHb": it references class "App\\Entity\\FavorisTuroial" but no such service exists.');
    }
}
