<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSXyzPYC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSXyzPYC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSXyzPYC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSXyzPYC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSXyzPYC\App_KernelDevDebugContainer([
    'container.build_hash' => 'SXyzPYC',
    'container.build_id' => '1ae1ed9f',
    'container.build_time' => 1682427389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSXyzPYC');
