<?php

namespace Container9SxSNYt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQrcodeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lrPeSHZ.App\Services\QrcodeService' shared service.
     *
     * @return \App\Services\QrcodeService
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lrPeSHZ": it references class "App\\Services\\QrcodeService" but no such service exists.');
    }
}
