<?php

namespace ContainerMhnqebu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3Aad2VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3_Aad2V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3_Aad2V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticator' => ['privates', '.errored.n_GAKL9', NULL, 'Cannot determine controller argument for "App\\Controller\\AllusersController::login()": the $authenticator argument is type-hinted with the non-existent class or interface: "App\\Controller\\LoginFormAuthenticator". Did you forget to add a use statement?'],
            'guardHandler' => ['privates', 'security.authentication.guard_handler', 'getSecurity_Authentication_GuardHandlerService', true],
            'userRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
        ], [
            'authenticator' => '?',
            'guardHandler' => '?',
            'userRepository' => 'App\\Repository\\AllusersRepository',
        ]);
    }
}
