<?php

namespace ContainerMhnqebu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_NGAKL9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.n_GAKL9' shared service.
     *
     * @return \App\Controller\LoginFormAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\AllusersController::login()": the $authenticator argument is type-hinted with the non-existent class or interface: "App\\Controller\\LoginFormAuthenticator". Did you forget to add a use statement?');
    }
}
