<?php

namespace ContainerM9CoVpv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ZN5QsWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6ZN5QsW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ZN5QsW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mr' => ['privates', '.errored.hlufCP2', NULL, 'Cannot determine controller argument for "App\\Controller\\ProduitsBackController::delete()": the $mr argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?'],
            'tutorielRepository' => ['privates', '.errored.Q6veYQc', NULL, 'Cannot determine controller argument for "App\\Controller\\ProduitsBackController::delete()": the $tutorielRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\TutorielRepository". Did you forget to add a use statement?'],
        ], [
            'mr' => '?',
            'tutorielRepository' => '?',
        ]);
    }
}
