<?php

namespace ContainerM9CoVpv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Q6veYQcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Q6veYQc' shared service.
     *
     * @return \App\Controller\TutorielRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ProduitsBackController::delete()": the $tutorielRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\TutorielRepository". Did you forget to add a use statement?');
    }
}
