<?php

namespace ContainerM9CoVpv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGrosmotsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YkIsf6u.App\Entity\Grosmots' shared service.
     *
     * @return \App\Entity\Grosmots
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.YkIsf6u": it references class "App\\Entity\\Grosmots" but no such service exists.');
    }
}
