<?php

namespace ContainerJxmHlSS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeteoConceptHCaptcha_HcaptchaFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'meteo_concept_h_captcha.hcaptcha_form_type' shared service.
     *
     * @return \MeteoConcept\HCaptchaBundle\Form\HCaptchaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'meteo-concept'.\DIRECTORY_SEPARATOR.'hcaptcha-bundle'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'HCaptchaType.php';

        return $container->services['meteo_concept_h_captcha.hcaptcha_form_type'] = new \MeteoConcept\HCaptchaBundle\Form\HCaptchaType(($container->services['meteo_concept_h_captcha.hcaptcha_value_fetcher'] ?? $container->load('getMeteoConceptHCaptcha_HcaptchaValueFetcherService')), '10000000-ffff-ffff-ffff-000000000001');
    }
}
