<?php

namespace ContainerJxmHlSS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPost4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o6b1BO2.App\Entity\Post' shared service.
     *
     * @return \App\Entity\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.o6b1BO2": it references class "App\\Entity\\Post" but no such service exists.');
    }
}
