<?php

namespace ContainerPSP28xa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLignepanierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TGOvGF5.App\Entity\Lignepanier' shared service.
     *
     * @return \App\Entity\Lignepanier
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TGOvGF5": it references class "App\\Entity\\Lignepanier" but no such service exists.');
    }
}
