<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4NSx1DB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4NSx1DB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4NSx1DB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4NSx1DB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4NSx1DB\App_KernelDevDebugContainer([
    'container.build_hash' => '4NSx1DB',
    'container.build_id' => '5c443ce0',
    'container.build_time' => 1683268751,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4NSx1DB');
