<?php

namespace Container23oLSu9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_User_Listener_LastLoginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.user.listener.last_login' shared service.
     *
     * @return \Sonata\UserBundle\Listener\LastLoginListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'sonata-project'.\DIRECTORY_SEPARATOR.'user-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Listener'.\DIRECTORY_SEPARATOR.'LastLoginListener.php';

        return $container->privates['sonata.user.listener.last_login'] = new \Sonata\UserBundle\Listener\LastLoginListener(($container->privates['sonata.user.manager.user'] ?? $container->load('getSonata_User_Manager_UserService')));
    }
}
