<?php

namespace Container5w83mbL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ROlNY4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ROlNY4_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ROlNY4_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'videoRepository' => ['privates', 'App\\Repository\\VideoRepository', 'getVideoRepositoryService', true],
            'videoentity' => ['privates', '.errored..service_locator.ROlNY4_.App\\Entity\\Video', NULL, 'Cannot autowire service ".service_locator.ROlNY4_": it references class "App\\Entity\\Video" but no such service exists.'],
        ], [
            'videoRepository' => 'App\\Repository\\VideoRepository',
            'videoentity' => 'App\\Entity\\Video',
        ]);
    }
}
