<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tutoriel extends \App\Entity\Tutoriel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'id_tutoriel', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'id_categorie', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'id_artist', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'pathimg', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'niveau', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'videos', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'ratingTutoriels'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'id_tutoriel', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'id_categorie', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'id_artist', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'pathimg', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'niveau', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'videos', '' . "\0" . 'App\\Entity\\Tutoriel' . "\0" . 'ratingTutoriels'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tutoriel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdArtist(): ?\App\Entity\allusers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdArtist', []);

        return parent::getIdArtist();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdArtist(?\App\Entity\allusers $id_artist): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdArtist', [$id_artist]);

        return parent::setIdArtist($id_artist);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategorie(): ?\App\Entity\category
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategorie', []);

        return parent::getIdCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategorie(?\App\Entity\category $id_categorie): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategorie', [$id_categorie]);

        return parent::setIdCategorie($id_categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getPathimg(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPathimg', []);

        return parent::getPathimg();
    }

    /**
     * {@inheritDoc}
     */
    public function setPathimg(string $pathimg): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathimg', [$pathimg]);

        return parent::setPathimg($pathimg);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(int $niveau): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideos', []);

        return parent::getVideos();
    }

    /**
     * {@inheritDoc}
     */
    public function addVideo(\App\Entity\Video $video): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVideo', [$video]);

        return parent::addVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVideo(\App\Entity\Video $video): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVideo', [$video]);

        return parent::removeVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getFavorisTuroials(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFavorisTuroials', []);

        return parent::getFavorisTuroials();
    }

    /**
     * {@inheritDoc}
     */
    public function addFavorisTuroial(\App\Entity\FavorisTuroial $favorisTuroial): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFavorisTuroial', [$favorisTuroial]);

        return parent::addFavorisTuroial($favorisTuroial);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFavorisTuroial(\App\Entity\FavorisTuroial $favorisTuroial): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFavorisTuroial', [$favorisTuroial]);

        return parent::removeFavorisTuroial($favorisTuroial);
    }

    /**
     * {@inheritDoc}
     */
    public function addIdArtist(\App\Entity\Allusers $idArtist): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdArtist', [$idArtist]);

        return parent::addIdArtist($idArtist);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdArtist(\App\Entity\Allusers $idArtist): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdArtist', [$idArtist]);

        return parent::removeIdArtist($idArtist);
    }

    /**
     * {@inheritDoc}
     */
    public function getRatingTutoriels(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRatingTutoriels', []);

        return parent::getRatingTutoriels();
    }

    /**
     * {@inheritDoc}
     */
    public function addRatingTutoriel(\App\Entity\RatingTutoriel $ratingTutoriel): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRatingTutoriel', [$ratingTutoriel]);

        return parent::addRatingTutoriel($ratingTutoriel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRatingTutoriel(\App\Entity\RatingTutoriel $ratingTutoriel): \App\Entity\Tutoriel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRatingTutoriel', [$ratingTutoriel]);

        return parent::removeRatingTutoriel($ratingTutoriel);
    }

}
