<?php

namespace ContainerWbB3sj6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_8ZU1Sv7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.8ZU1Sv7' shared service.
     *
     * @return \App\Controller\FlashyNotifier
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\PanierController::ajouterProduitAuPanier()": the $flashy argument is type-hinted with the non-existent class or interface: "App\\Controller\\FlashyNotifier". Did you forget to add a use statement?');
    }
}
