<?php

namespace ContainerCKGMCp9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ule7WwGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ule7WwG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ule7WwG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allusersRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
            'lignepanier' => ['privates', '.errored..service_locator.ule7WwG.App\\Entity\\Lignepanier', NULL, 'Cannot autowire service ".service_locator.ule7WwG": it references class "App\\Entity\\Lignepanier" but no such service exists.'],
        ], [
            'allusersRepository' => 'App\\Repository\\AllusersRepository',
            'lignepanier' => 'App\\Entity\\Lignepanier',
        ]);
    }
}
