<?php

namespace ContainerCKGMCp9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChallenge3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o4rXWnE.App\Entity\Challenge' shared service.
     *
     * @return \App\Entity\Challenge
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.o4rXWnE": it references class "App\\Entity\\Challenge" but no such service exists.');
    }
}
