<?php

namespace Container90BuR4V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZcyIm2ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZcyIm2Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZcyIm2Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allusersRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
            'alluserscontroller' => ['privates', '.errored.gIM_FJb', NULL, 'Cannot determine controller argument for "App\\Controller\\DemandetravailController::index()": the $alluserscontroller argument is type-hinted with the non-existent class or interface: "App\\Controller\\AllusersCotroller". Did you forget to add a use statement?'],
            'demandetravailRepository' => ['privates', 'App\\Repository\\DemandetravailRepository', 'getDemandetravailRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'allusersRepository' => 'App\\Repository\\AllusersRepository',
            'alluserscontroller' => '?',
            'demandetravailRepository' => 'App\\Repository\\DemandetravailRepository',
            'paginator' => '?',
        ]);
    }
}
