<?php

namespace Container90BuR4V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_FvzMiNKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.fvzMiNK' shared service.
     *
     * @return \App\Controller\AllusersCotroller
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\DemandetravailController::edit()": the $alluserscontroller argument is type-hinted with the non-existent class or interface: "App\\Controller\\AllusersCotroller". Did you forget to add a use statement?');
    }
}
