<?php

namespace Container90BuR4V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GLiNROService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gLiNRO_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gLiNRO_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allusersRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
            'alluserscontroller' => ['privates', '.errored.OqQgtpC', NULL, 'Cannot determine controller argument for "App\\Controller\\StudiodashboardController::offres()": the $alluserscontroller argument is type-hinted with the non-existent class or interface: "App\\Controller\\AllusersCotroller". Did you forget to add a use statement?'],
            'offretravailRepository' => ['privates', 'App\\Repository\\OffretravailRepository', 'getOffretravailRepositoryService', true],
        ], [
            'allusersRepository' => 'App\\Repository\\AllusersRepository',
            'alluserscontroller' => '?',
            'offretravailRepository' => 'App\\Repository\\OffretravailRepository',
        ]);
    }
}
