<?php

namespace Container7uCyxht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UzTwEQDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uzTwEQD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uzTwEQD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'panierRep' => ['privates', 'App\\Repository\\PanierRepository', 'getPanierRepositoryService', true],
            'produit' => ['privates', '.errored..service_locator.uzTwEQD.App\\Entity\\Produits', NULL, 'Cannot autowire service ".service_locator.uzTwEQD": it references class "App\\Entity\\Produits" but no such service exists.'],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
        ], [
            'Normalizer' => '?',
            'entityManager' => '?',
            'panierRep' => 'App\\Repository\\PanierRepository',
            'produit' => 'App\\Entity\\Produits',
            'produitRepository' => 'App\\Repository\\ProduitsRepository',
        ]);
    }
}
