<?php

namespace Container7uCyxht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OxHi1QWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oxHi1QW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oxHi1QW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'normalizer' => ['privates', '.errored.auql5ZH', NULL, 'Cannot determine controller argument for "App\\Controller\\PostController::newpostjson()": the $normalizer argument is type-hinted with the non-existent class or interface: "App\\Controller\\NormalizerInterface". Did you forget to add a use statement?'],
        ], [
            'normalizer' => '?',
        ]);
    }
}
