<?php

namespace Container7uCyxht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KOlj7hgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KOlj7hg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KOlj7hg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allusersRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
            'grosmot' => ['privates', '.errored..service_locator.KOlj7hg.App\\Entity\\Grosmots', NULL, 'Cannot autowire service ".service_locator.KOlj7hg": it references class "App\\Entity\\Grosmots" but no such service exists.'],
        ], [
            'allusersRepository' => 'App\\Repository\\AllusersRepository',
            'grosmot' => 'App\\Entity\\Grosmots',
        ]);
    }
}
