<?php

namespace ContainerTdh8F9F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P1B2DkyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p1B2Dky' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p1B2Dky'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allusersRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
            'demandetravail' => ['privates', '.errored..service_locator.p1B2Dky.App\\Entity\\Demandetravail', NULL, 'Cannot autowire service ".service_locator.p1B2Dky": it references class "App\\Entity\\Demandetravail" but no such service exists.'],
        ], [
            'allusersRepository' => 'App\\Repository\\AllusersRepository',
            'demandetravail' => 'App\\Entity\\Demandetravail',
        ]);
    }
}
