<?php

namespace ContainerXaJFzVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZA44DHyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zA44DHy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zA44DHy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'banRepository' => ['privates', 'App\\Repository\\BanRepository', 'getBanRepositoryService', true],
        ], [
            'banRepository' => 'App\\Repository\\BanRepository',
        ]);
    }
}
