<?php

namespace ContainerZaSC0Xt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QzFynt4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qzFynt4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qzFynt4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alluser' => ['privates', '.errored..service_locator.qzFynt4.App\\Entity\\Allusers', NULL, 'Cannot autowire service ".service_locator.qzFynt4": it references class "App\\Entity\\Allusers" but no such service exists.'],
            'twilioClient' => ['privates', 'twilio.client', 'getTwilio_ClientService', true],
        ], [
            'alluser' => 'App\\Entity\\Allusers',
            'twilioClient' => '?',
        ]);
    }
}
