<?php

namespace ContainerKYhvcWG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffretravailarchiveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4NXkpsl.App\Entity\Offretravailarchive' shared service.
     *
     * @return \App\Entity\Offretravailarchive
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.4NXkpsl": it references class "App\\Entity\\Offretravailarchive" but no such service exists.');
    }
}
