<?php

namespace ContainerKYhvcWG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffretravail2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qWtjbJS.App\Entity\Offretravail' shared service.
     *
     * @return \App\Entity\Offretravail
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qWtjbJS": it references class "App\\Entity\\Offretravail" but no such service exists.');
    }
}
