<?php

namespace ContainerHtz8qR0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GatlMccService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GatlMcc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GatlMcc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'demandetravail' => ['privates', '.errored..service_locator.GatlMcc.App\\Entity\\Demandetravail', NULL, 'Cannot autowire service ".service_locator.GatlMcc": it references class "App\\Entity\\Demandetravail" but no such service exists.'],
            'demandetravailRepository' => ['privates', 'App\\Repository\\DemandetravailRepository', 'getDemandetravailRepositoryService', true],
            'mot' => ['privates', 'App\\Repository\\GrosmotsRepository', 'getGrosmotsRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'demandetravail' => 'App\\Entity\\Demandetravail',
            'demandetravailRepository' => 'App\\Repository\\DemandetravailRepository',
            'mot' => 'App\\Repository\\GrosmotsRepository',
        ]);
    }
}
