<?php

namespace ContainerYRsqUZA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandetravailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._._y3dG.App\Entity\Demandetravail' shared service.
     *
     * @return \App\Entity\Demandetravail
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._._y3dG": it references class "App\\Entity\\Demandetravail" but no such service exists.');
    }
}
