<?php

namespace ContainerWkHsdiq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideo3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._EeCc6U.App\Entity\Video' shared service.
     *
     * @return \App\Entity\Video
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._EeCc6U": it references class "App\\Entity\\Video" but no such service exists.');
    }
}
