<?php

namespace Container3ugAsUT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostLikeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rXk8ooy.App\Entity\PostLike' shared service.
     *
     * @return \App\Entity\PostLike
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.rXk8ooy": it references class "App\\Entity\\PostLike" but no such service exists.');
    }
}
