<?php

namespace Container9Tq9S9N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BhogO86Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bhogO86' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bhogO86'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'favorisTuroialRepository' => ['privates', 'App\\Repository\\FavorisTuroialRepository', 'getFavorisTuroialRepositoryService', true],
        ], [
            'favorisTuroialRepository' => 'App\\Repository\\FavorisTuroialRepository',
        ]);
    }
}
