<?php

namespace Container2sehdub;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_89ET3ObService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.89ET3Ob' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.89ET3Ob'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allusersRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
            'post' => ['privates', '.errored..service_locator.89ET3Ob.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.89ET3Ob": it references class "App\\Entity\\Post" but no such service exists.'],
        ], [
            'allusersRepository' => 'App\\Repository\\AllusersRepository',
            'post' => 'App\\Entity\\Post',
        ]);
    }
}
