<?php

namespace Container2sehdub;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RqFyUmHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RqFyUmH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RqFyUmH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allusersRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
            'postLike' => ['privates', '.errored..service_locator.RqFyUmH.App\\Entity\\PostLike', NULL, 'Cannot autowire service ".service_locator.RqFyUmH": it references class "App\\Entity\\PostLike" but no such service exists.'],
        ], [
            'allusersRepository' => 'App\\Repository\\AllusersRepository',
            'postLike' => 'App\\Entity\\PostLike',
        ]);
    }
}
