<?php

namespace Container2sehdub;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_R8k6i7wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.R8k6i7w' shared service.
     *
     * @return \App\Controller\NormalizerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\PostController::editpostjson()": the $Normalizer argument is type-hinted with the non-existent class or interface: "App\\Controller\\NormalizerInterface". Did you forget to add a use statement?');
    }
}
