<?php

namespace Container2sehdub;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_XkqK92eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.XkqK92e' shared service.
     *
     * @return \App\Controller\NormalizerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\PostController::DeletePostJson()": the $Normalizer argument is type-hinted with the non-existent class or interface: "App\\Controller\\NormalizerInterface". Did you forget to add a use statement?');
    }
}
