<?php

namespace Container2sehdub;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getView3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Jb_WVsE.App\Entity\View' shared service.
     *
     * @return \App\Entity\View
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Jb_WVsE": it references class "App\\Entity\\View" but no such service exists.');
    }
}
