<?php

namespace ContainerO0mQVxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IkPfdHsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IkPfdHs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IkPfdHs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'challengeRepository' => ['privates', 'App\\Repository\\ChallengeRepository', 'getChallengeRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'mr' => ['services', 'doctrine', 'getDoctrineService', false],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'challengeRepository' => 'App\\Repository\\ChallengeRepository',
            'doctrine' => '?',
            'mr' => '?',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]);
    }
}
