<?php

namespace ContainerO0mQVxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_XakE3zgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.xakE3zg' shared service.
     *
     * @return \App\Controller\EvemtRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ChallengeController::calendar()": the $evemtRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\EvemtRepository". Did you forget to add a use statement?');
    }
}
