<?php

namespace ContainerO0mQVxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LYk9ljtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lYk9ljt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lYk9ljt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evemtRepository' => ['privates', '.errored.xakE3zg', NULL, 'Cannot determine controller argument for "App\\Controller\\ChallengeController::calendar()": the $evemtRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\EvemtRepository". Did you forget to add a use statement?'],
        ], [
            'evemtRepository' => '?',
        ]);
    }
}
