<?php

namespace ContainerXtGnqIO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsTranslation_Controller_ApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'jms_translation.controller.api_controller' shared service.
     *
     * @return \JMS\TranslationBundle\Controller\ApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'jms'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ApiController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'jms'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ConfigFactory.php';

        return $container->services['jms_translation.controller.api_controller'] = new \JMS\TranslationBundle\Controller\ApiController(($container->services['jms_translation.config_factory'] ?? ($container->services['jms_translation.config_factory'] = new \JMS\TranslationBundle\Translation\ConfigFactory([]))), ($container->services['jms_translation.updater'] ?? $container->load('getJmsTranslation_UpdaterService')));
    }
}
