<?php

namespace ContainerEYgW7gV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ymg9CHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ymg_9CH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ymg_9CH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lignepanierRepository' => ['privates', 'App\\Repository\\LignepanierRepository', 'getLignepanierRepositoryService', true],
            'panier' => ['privates', '.errored..service_locator.Ymg_9CH.App\\Entity\\Panier', NULL, 'Cannot autowire service ".service_locator.Ymg_9CH": it references class "App\\Entity\\Panier" but no such service exists.'],
        ], [
            'lignepanierRepository' => 'App\\Repository\\LignepanierRepository',
            'panier' => 'App\\Entity\\Panier',
        ]);
    }
}
