<?php

namespace ContainerEYgW7gV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ymg_9CH.App\Entity\Panier' shared service.
     *
     * @return \App\Entity\Panier
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Ymg_9CH": it references class "App\\Entity\\Panier" but no such service exists.');
    }
}
