<?php

namespace ContainerUmc7c3y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PvQF2fmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pvQF2fm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pvQF2fm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ac' => ['services', 'App\\Controller\\AllusersController', 'getAllusersControllerService', true],
            'banRepository' => ['privates', 'App\\Repository\\BanRepository', 'getBanRepositoryService', true],
        ], [
            'ac' => 'App\\Controller\\AllusersController',
            'banRepository' => 'App\\Repository\\BanRepository',
        ]);
    }
}
