<?php

namespace ContainerDaJtot1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UO_HMV7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uO.HMV7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uO.HMV7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allusersRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
            'participation' => ['privates', '.errored..service_locator.uO.HMV7.App\\Entity\\Participation', NULL, 'Cannot autowire service ".service_locator.uO.HMV7": it references class "App\\Entity\\Participation" but no such service exists.'],
            'participationRepository' => ['privates', 'App\\Repository\\ParticipationRepository', 'getParticipationRepositoryService', true],
        ], [
            'allusersRepository' => 'App\\Repository\\AllusersRepository',
            'participation' => 'App\\Entity\\Participation',
            'participationRepository' => 'App\\Repository\\ParticipationRepository',
        ]);
    }
}
