<?php

namespace ContainerSPpsh7p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllusers2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._KOe8P1.App\Entity\Allusers' shared service.
     *
     * @return \App\Entity\Allusers
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._KOe8P1": it references class "App\\Entity\\Allusers" but no such service exists.');
    }
}
