<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHwwWQwb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHwwWQwb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHwwWQwb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHwwWQwb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHwwWQwb\App_KernelDevDebugContainer([
    'container.build_hash' => 'HwwWQwb',
    'container.build_id' => 'a893354f',
    'container.build_time' => 1682628500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHwwWQwb');
