<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5w83mbL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5w83mbL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5w83mbL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5w83mbL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5w83mbL\App_KernelDevDebugContainer([
    'container.build_hash' => '5w83mbL',
    'container.build_id' => 'b88ddf7e',
    'container.build_time' => 1681871334,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5w83mbL');
