<?php

namespace ContainerRuPFfqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FbYC5dEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FbYC5dE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FbYC5dE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'allusersRepository' => ['privates', 'App\\Repository\\AllusersRepository', 'getAllusersRepositoryService', true],
            'offretravailarchive' => ['privates', '.errored..service_locator.FbYC5dE.App\\Entity\\Offretravailarchive', NULL, 'Cannot autowire service ".service_locator.FbYC5dE": it references class "App\\Entity\\Offretravailarchive" but no such service exists.'],
        ], [
            'allusersRepository' => 'App\\Repository\\AllusersRepository',
            'offretravailarchive' => 'App\\Entity\\Offretravailarchive',
        ]);
    }
}
