<?php

namespace ContainerICS4CEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jo1LeSsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jo1LeSs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jo1LeSs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'mr' => ['services', 'doctrine', 'getDoctrineService', false],
            'ratingRepository' => ['privates', '.errored.sjrJdWe', NULL, 'Cannot determine controller argument for "App\\Controller\\FavorisTuroialMobileController::fetchCountFavorisTutoriel()": the $ratingRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\RatingTutorielRepository". Did you forget to add a use statement?'],
            'tutorielRepository' => ['privates', 'App\\Repository\\TutorielRepository', 'getTutorielRepositoryService', true],
        ], [
            'Normalizer' => '?',
            'doctrine' => '?',
            'mr' => '?',
            'ratingRepository' => '?',
            'tutorielRepository' => 'App\\Repository\\TutorielRepository',
        ]);
    }
}
